@startuml 複数のTwitterアカウントにログインできる

!include ../sequence.conf 

actor ユーザー

note left
### 基本コース

システムは「アカウント一覧」ページを表示する。
ユーザーは「Twitterアカウントの追加」ボタンをクリックする。
システムはTwitterのＯＡｕｔｈを表示する。
ユーザーはログインする。
システムはリダイレクトURLを取得し、アクセストークンを読み取る。
システムはアカウント名を保存し、Twitterアカウントを作成。
システムはアカウント一覧を取得する。
システムは「アカウント一覧」ページを表示する。

### 代替コース

Twitterへのログインキャンセル：
OAuthを閉じる。
アクセストークンの取得を失敗：
アカウントの登録に失敗しましたを表示
アカウント名の取得を失敗：
アカウントの登録に失敗しましたを表示

endnote

boundary "「アカウント一覧」ページ" as AccountListWindow
boundary "「OAuth on Twitter」ページ" as TwitterOAuthWindow
control TwitterService
control TwitterClient
control TwitterAccountRepository
control FacebookAccountRepository
entity TwitterAccount
entity FacebookAccount

ユーザー -> AccountListWindow : 「Twitterアカウントの追加」ボタンをクリック
AccountListWindow -> TwitterOAuthWindow : Show()
activate TwitterOAuthWindow
alt ログインキャンセル
ユーザー -> TwitterOAuthWindow : 「閉じる」ボタンを押す
TwitterOAuthWindow -> TwitterOAuthWindow : Close()
end
ユーザー -> TwitterOAuthWindow : ログイン
TwitterOAuthWindow -> TwitterOAuthWindow : redirectUrl = getRedirectUrl
alt アクセストークンの取得に失敗
TwitterOAuthWindow -> TwitterOAuthWindow : showAuthorizationErrorMessage()
end
TwitterOAuthWindow -> TwitterService : configureFromRedirectUrl(redirectUrl)
activate TwitterService
TwitterOAuthWindow -> TwitterService : account = createTwitterAccount()
TwitterService -> TwitterClient : getAccountName()
alt アカウント名の取得に失敗
TwitterOAuthWindow -> TwitterOAuthWindow : showAuthorizationErrorMessage()
end
activate TwitterClient
deactivate TwitterClient
TwitterService -> TwitterAccount : new
activate TwitterAccount
deactivate TwitterAccount
deactivate TwitterClient
deactivate TwitterService
TwitterOAuthWindow -> TwitterAccountRepository : save(account)
activate TwitterAccountRepository
TwitterOAuthWindow -> TwitterOAuthWindow : close()
deactivate TwitterOAuthWindow
AccountListWindow -> TwitterAccountRepository : findAll()
TwitterAccountRepository -> TwitterAccount : create()
AccountListWindow -> FacebookAccountRepository : findAll()
FacebookAccountRepository -> FacebookAccount : create()
activate FacebookAccountRepository
deactivate FacebookAccountRepository
deactivate TwitterAccountRepository
AccountListWindow -> ユーザー : アカウント一覧の表示

@enduml