@startuml 複数のTwitterアカウントにログインできる

!include ../sequence.conf 

actor ユーザー

note left
### 基本コース

システムは「アカウント一覧」ページを表示する。
ユーザーは「Twitterアカウントの追加」ボタンをクリックする。
システムはTwitterのＯＡｕｔｈを表示する。
ユーザーはログインする。
システムはリダイレクトURLを取得し、アクセストークンを読み取る。
システムはアカウント名を保存し、Twitterアカウントを作成。
システムはアカウント一覧を取得する。
システムは「アカウント一覧」ページを表示する。

### 代替コース

Twitterへのログインキャンセル：
OAuthを閉じる。
アクセストークンの取得を失敗：
アカウントの登録に失敗しましたを表示
アカウント名の取得を失敗：
アカウントの登録に失敗しましたを表示

endnote

boundary "「アカウント一覧」ページ" as AccountListWindow
boundary "「OAuth on Twitter」ページ" as TwitterOAuthWindow
control TwitterOAuthProvider
control CreateTwitterAccountFromOAuthCredentialsUsecase
control TwitterClient
control TwitterAccountRepository
control FacebookAccountRepository
entity TwitterAccount
entity FacebookAccount

activate AccountListWindow
ユーザー -> AccountListWindow : 「Twitterアカウントの追加」ボタンをクリック
AccountListWindow -> TwitterOAuthWindow : Show()
activate TwitterOAuthWindow
alt ログインキャンセル
ユーザー -> TwitterOAuthWindow : 「閉じる」ボタンを押す
TwitterOAuthWindow -> TwitterOAuthWindow : Close()
end
ユーザー -> TwitterOAuthWindow : ログイン
TwitterOAuthWindow -> TwitterOAuthProvider : oauthUrl = OAuthUrl()
activate TwitterOAuthProvider
TwitterOAuthWindow -> TwitterOAuthProvider : oauthCrednetials = FetchOAuthCredentialsFromRedirectUrl(redirectUrl)
deactivate TwitterOAuthProvider
alt アクセストークンの取得に失敗
TwitterOAuthWindow -> TwitterOAuthWindow : showAuthorizationErrorMessage()
end
TwitterOAuthWindow -> CreateTwitterAccountFromOAuthCredentialsUsecase : exec(oauthCredentials)
activate CreateTwitterAccountFromOAuthCredentialsUsecase
activate TwitterClient
CreateTwitterAccountFromOAuthCredentialsUsecase -> TwitterClient : getAccountName()
alt アカウント名の取得に失敗
TwitterOAuthWindow -> TwitterOAuthWindow : showAuthorizationErrorMessage()
end
CreateTwitterAccountFromOAuthCredentialsUsecase -> TwitterAccount : new
activate TwitterAccount
deactivate TwitterAccount
deactivate TwitterClient
CreateTwitterAccountFromOAuthCredentialsUsecase -> TwitterAccountRepository : save(account)
activate TwitterAccountRepository
deactivate CreateTwitterAccountFromOAuthCredentialsUsecase
TwitterOAuthWindow -> TwitterOAuthWindow : close()
TwitterOAuthWindow -> AccountListWindow : OnClose()
deactivate TwitterOAuthWindow
AccountListWindow -> TwitterAccountRepository : findAll()
TwitterAccountRepository -> TwitterAccount : create()
AccountListWindow -> FacebookAccountRepository : findAll()
activate FacebookAccountRepository
FacebookAccountRepository -> FacebookAccount : create()
deactivate FacebookAccountRepository
deactivate TwitterAccountRepository
AccountListWindow -> ユーザー : アカウント一覧の表示

@enduml