@startuml all

!include window.pu
!include provider.pu
!include model.pu

class OAuthCredentials{
    + string AccessToken
    + string AccessTokenSecret
}
interface  ICreateAccountFromOAuthCredentialsUseCase{
    + void exec(OAuthCredentials credentials)
}
interface  IOAuthProvider{
    + string OAuthUrl()
    + OAuthCredentials FetchOAuthCredentialsFromRedirectUrl(string redirectUrl)
}
class TwitterOAuthProvider{

}
class  CreateTwitterAccountFromOAuthCredentialsUseCase{
}

class TwitterClient{
    + configureFromRedirectUrl(Uri redirectUrl)
    + getAccountName()
    + getIconPath()
}
interface ITwitterAccountRepository{
    + void add(TwitterAccount account)
    + List<TwitterAccount> findAll()
}
interface IFacebookAccountRepository{
    + FacebookAccount findAll()
}

class TwitterJsonDao{
    - List<TwitterAccount> data
    + void add(TwitterAccount account)
    + List<TwitterAccount> findAll()
}
class FacebookJsonDao{
    - List<FacebookAccount> data
    + void add(FacebookAccount account)
    + List<FacebookAccount> findAll()
}

AccountListWindow ..> ITwitterAccountRepository
AccountListWindow ..> IFacebookAccountRepository
OAuthWindow ..> IOAuthProvider
IOAuthProvider ..> OAuthCredentials
IOAuthProvider <|-- TwitterOAuthProvider
OAuthWindow ..> ICreateAccountFromOAuthCredentialsUseCase
ICreateAccountFromOAuthCredentialsUseCase ..> OAuthCredentials
ICreateAccountFromOAuthCredentialsUseCase <|-- CreateTwitterAccountFromOAuthCredentialsUseCase
CreateTwitterAccountFromOAuthCredentialsUseCase ..> TwitterClient
CreateTwitterAccountFromOAuthCredentialsUseCase ..> TwitterAccountRepository
CreateTwitterAccountFromOAuthCredentialsUseCase ..> TwitterAccount
TwitterClient ..> System.Net.Http.HttpClient
ITwitterAccountRepository ..> TwitterAccount
IFacebookAccountRepository ..> FacebookAccount
TwitterAccountRepository --|> ITwitterAccountRepository
FacebookAccountRepository --|> IFacebookAccountRepository
TwitterAccountRepository ..> TwitterJsonDao
FacebookAccountRepository ..> FacebookJsonDao
TwitterJsonDao ..> JsonProvider
FacebookJsonDao ..> JsonProvider
TwitterJsonDao ..> TwitterAccount
FacebookJsonDao ..> FacebookAccount
@enduml