@startuml all

!include window.pu
!include provider.pu
!include model.pu

interface  TwitterAccountFactory{
    + TwitterAccount createFromRedirectUri(Uri redirectUrl)
}

class  TwitterAccountFactoryImpl{
}

class TwitterClient{
    + configureFromRedirectUrl(Uri redirectUrl)
    + getAccountName()
    + getIconPath()
}
interface TwitterAccountRepository{
    + void add(TwitterAccount account)
    + List<TwitterAccount> findAll()
}
interface FacebookAccountRepository{
    + FacebookAccount findAll()
}

class TwitterJsonDao{
    - List<TwitterAccount> data
    + void add(TwitterAccount account)
    + List<TwitterAccount> findAll()
    + void save()
}
class FacebookJsonDao{
    - List<FacebookAccount> data
    + void add(FacebookAccount account)
    + List<FacebookAccount> findAll()
    + void save()
}

AccountListWindow ..> TwitterAccountRepository
AccountListWindow ..> FacebookAccountRepository
TwitterOAuthWindow ..> TwitterAccountFactory
TwitterAccountFactoryImpl --|> TwitterAccountFactory
TwitterAccountFactoryImpl ..> TwitterClient
TwitterClient ..> System.Net.Http.HttpClient
TwitterAccountFactory ..> TwitterAccount
TwitterAccountRepository ..> TwitterAccount
FacebookAccountRepository ..> FacebookAccount
TwitterAccountRepositoryImpl --|> TwitterAccountRepository
FacebookAccountRepositoryImpl --|> FacebookAccountRepository
TwitterAccountRepositoryImpl ..> TwitterJsonDao
FacebookAccountRepositoryImpl ..> FacebookJsonDao
TwitterJsonDao ..> JsonProvider
FacebookJsonDao ..> JsonProvider
TwitterJsonDao ..> TwitterAccount
FacebookJsonDao ..> FacebookAccount
@enduml