@startuml window

class Window

class AccountListWindow{
    - openTwitterOAuthDialog()
}

class OAuthWindow{
    - getRedirectUrl()
    - showAuthorizationErrorMessage()
}

Window <|-- AccountListWindow
Window <|-- OAuthWindow
AccountListWindow ..> OAuthWindow

@enduml