@startuml ドメインモデル

object ユーザー
interface TwitterAction {
    + Long ownerId
}
interface FacebookAction {
    + Long ownerId
}

class TwitterAccount {
    + Long id
    + string userName
    + string iconPath
}

class TwitterAccountCreadential{
    + string accessToken
    + string accessTokenSecret
}

class TwitterTimeline {

}
class TwitterList {
    + listId
}
class TwitterListTimeline {
    + listId
}
class TwitterDMList {

}
class TwitterDM {

}
class TwitterNotification {

}
class TwitterSearch {
    + string searchParam
}
class TwitterUserPage {
    + string userId
}
class FacebookAccount {
    + Long id
    + string accessToken
    + string userName
    + string iconPath
}
class FacebookTimeline {

}
class FacebookUserPage {

}
class FacebookSearch {

}
class FacebookMessanger {

}
class FacebookNotification {

}

ユーザー o-- TwitterAccount
ユーザー o-- FacebookAccount
TwitterAccount o-- TwitterAction
TwitterAccount o-- TwitterAccountCreadential
TwitterAction --|> TwitterTimeline
TwitterAction --|> TwitterList
TwitterAction --|> TwitterListTimeline
TwitterList o-- TwitterListTimeline
TwitterAction --|> TwitterDMList
TwitterAction --|> TwitterDM
TwitterDMList o-- TwitterDM
TwitterAction --|> TwitterNotification
TwitterAction --|> TwitterSearch
TwitterAction --|> TwitterUserPage
FacebookAccount o-- FacebookAction
FacebookAction --|> FacebookTimeline
FacebookAction --|> FacebookMessanger
FacebookAction --|> FacebookNotification
FacebookAction --|> FacebookSearch
FacebookAction --|> FacebookUserPage

@enduml