@startuml	ユースケースパッケージ

package 一般 {
	(列を追加できる)
	(Twitterのタイムラインを列を追加できる)
	(Facebookのタイムラインを列を追加できる)
	(Facebookにログインできる)
	(複数のTwitterアカウントにログインできる)
}

package Twitter {
	(タイムラインを見れる)
	(リストのタイムラインを見れる)
	(ユーザーのプロフィールを見れる)
	(フォローできる)
	(ブロックできる)
	(DMで連絡をとれる)
	(通知が見れる)
	(検索できる)
}

package Facebook {
	(タイムラインが見れる)
	(通知が見れる)
	(検索できる)
	(ユーザーのプロフィールを見れる)
	(フォローできる)
}

@enduml