@startuml	ユースケースパッケージ

package 一般 {
	(列を追加する)
	(Twitterのタイムラインを列を追加する)
	(Facebookのタイムラインを列を追加する)
	(Facebookにログインする)
	(複数のTwitterアカウントにログインする)
}

package Twitter {
	(タイムラインを見る)
	(リストのタイムラインを見る)
	(ユーザーのプロフィールを見る)
	(フォローする)
	(ブロックする)
	(DMで連絡をとる)
	(通知が見る)
	(検索する)
}

package Facebook {
	(タイムラインが見る)
	(通知が見る)
	(検索する)
	(ユーザーのプロフィールを見る)
	(フォローする)
}

@enduml