@startuml	ユースケースパッケージ

package 一般 {
	(列で機能を表示する)
}

package Twitter {
	(タイムラインを見れる)
	(リストのタイムラインを見れる)
	(ユーザーのプロフィールを見れる)
	(フォローできる)
	(ブロックできる)
	(DMで連絡をとれる)
	(通知が見れる)
	(検索できる)
	(フォローできる)
}

package Facebook {
	(タイムラインが見れる)
	(通知が見れる)
	(検索できる)
	(ユーザーのプロフィールを見れる)
	(フォローできる)
}

@enduml