@startuml 複数のTwitterアカウントにログインする

!include ../robustness.conf 

actor ユーザー

note left
### 基本コース

システムは「アカウント一覧」ページを表示する。
ユーザーは「Twitterアカウントの追加」ボタンをクリックする。
システムはTwitterのＯＡｕｔｈを表示する。
ユーザーはログインする。
システムはリダイレクトURLを取得し、アクセストークンを読み取る。
システムはアカウント名を保存し、Twitterアカウントを作成。
システムはアカウント一覧を取得する。
システムは「アカウント一覧」ページを表示する。

### 代替コース

Twitterへのログインキャンセル：
OAuthを閉じる。
アクセストークンの取得を失敗：
アカウントの登録に失敗しましたを表示
アカウント名の取得を失敗：
アカウントの登録に失敗しましたを表示

endnote

boundary "「アカウント一覧」ページ" as accountListPage
boundary "「OAuth on Twitter」ページ" as twitterOAuthPage
control TwitterのOAuthを起動する
control リダイレクトURLを取得
control アクセストークンを読み取る
control アカウント名を取得
control Twitterアカウントの作成
control すべてのアカウントを取得
entity Twitterアカウント
entity Facebookアカウント

control "「OAuth on Twitter」ページを閉じる" as closeTwitterOAuthPage #Grey
control "「アカウントの登録に失敗しました」を表示" as showOAuthErrorMsg #Grey

ユーザー --> accountListPage
accountListPage --> TwitterのOAuthを起動する : 「Twitterアカウントの追加」ボタンをクリックする
TwitterのOAuthを起動する --> twitterOAuthPage
twitterOAuthPage --> closeTwitterOAuthPage : ログインをキャンセルする
closeTwitterOAuthPage --> accountListPage
twitterOAuthPage --> リダイレクトURLを取得 : ログインする
リダイレクトURLを取得 --> アクセストークンを読み取る
アクセストークンを読み取る --> アカウント名を取得
アクセストークンを読み取る --> showOAuthErrorMsg : 失敗
アカウント名を取得 --> Twitterアカウントの作成
アカウント名を取得 --> showOAuthErrorMsg : 失敗
showOAuthErrorMsg --> accountListPage
Twitterアカウントの作成 -- Twitterアカウント
Twitterアカウントの作成 --> すべてのアカウントを取得
すべてのアカウントを取得 -- Facebookアカウント
すべてのアカウントを取得 -- Twitterアカウント
すべてのアカウントを取得 --> accountListPage

@enduml